"""
cli.py — command-line entry point; routes to agent or script mode, then emits.

exports: main() -> int | parse_args(settings) -> Namespace
         build_pr_description(result, dag_id, target_table, ...) -> str
used_by: pyproject.toml → datahub-dag console script | generate_dag.py
rules:   Both modes MUST return an identical GenerationResult — everything
         downstream (_emit_result, _create_pr) is shared and mode-agnostic.
         _emit_result rejects DAG IDs containing path separators; keep that
         guard, it is the only thing stopping --dag-id path traversal.
"""
from __future__ import annotations

import argparse
import shlex
import subprocess
from dataclasses import replace
from pathlib import Path

from dag_generator.airflow import render_dag
from dag_generator.config import Settings, load_settings
from dag_generator.datahub import DataHubClient, _urn_to_table_name
from dag_generator.lineage import topological_sort, transitive_reduction
from dag_generator.models import DatasetNode, GenerationResult, QualityCheck
from dag_generator.policies import recommended_quality_checks, requires_freshness_check


def parse_args(settings: Settings) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate an Airflow DAG from DataHub lineage"
    )
    target_group = parser.add_mutually_exclusive_group(required=True)
    target_group.add_argument("--target", metavar="TABLE")
    target_group.add_argument("--urn", metavar="URN")
    parser.add_argument("--instance", default="nyc_taxi", metavar="INSTANCE")
    parser.add_argument("--dag-id", metavar="DAG_ID")
    parser.add_argument("--schedule", default="@daily")
    parser.add_argument("--output", default="dags", metavar="DIR")
    parser.add_argument(
        "--server",
        default=settings.datahub_server,
        help="DataHub GMS URL (default: DATAHUB_SERVER or localhost:8080)",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--writeback",
        action="store_true",
        help="Write dag_managed provenance to DataHub (disabled by default)",
    )
    parser.add_argument(
        "--no-writeback",
        action="store_false",
        dest="writeback",
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--mode", choices=["agent", "script"], default="agent")
    parser.add_argument(
        "--provider",
        choices=["openrouter", "anthropic"],
        default="openrouter",
    )
    parser.add_argument("--model", metavar="MODEL")
    parser.add_argument(
        "--pr",
        action="store_true",
        help="Create a Git branch and open a GitHub PR with the generated DAG",
    )
    parser.add_argument(
        "--pr-base",
        default="main",
        metavar="BRANCH",
        help="Base branch for the PR (default: main)",
    )
    parser.add_argument(
        "--dags-dir",
        default="dags",
        metavar="DIR",
        help="Tracked directory for PR mode (default: dags/)",
    )
    parser.set_defaults(writeback=False)
    return parser.parse_args()


def build_pr_description(
    result: GenerationResult,
    dag_id: str,
    target_table: str,
    platform_instance: str,
    schedule: str,
    dags_dir: str,
) -> str:
    nodes_by_urn = {node.urn: node for node in result.sorted_nodes}
    checks_by_urn: dict[str, list[QualityCheck]] = {}
    for check in result.quality_checks:
        checks_by_urn.setdefault(check.after_urn, []).append(check)

    lines = [
        "## Generated by DataHub DAG Generator Agent",
        "",
        f"**Target:** `{target_table}` @ `{platform_instance}`  ",
        f"**DAG ID:** `{dag_id}`  ",
        f"**Schedule:** `{schedule}`",
        "",
        "### Pipeline discovered from DataHub lineage",
        "",
        "| Stage | Table | Upstream | Metadata signals | Tasks added |",
        "|---|---|---|---|---|",
    ]

    for i, node in enumerate(result.sorted_nodes):
        upstream_names = [
            nodes_by_urn[u].simple_name
            for u in node.upstream_urns
            if u in nodes_by_urn
        ]
        upstream_str = ", ".join(f"`{n}`" for n in upstream_names) or "—"

        signals = []
        if node.tags:
            signals.append(f"tags: {', '.join(f'`{t}`' for t in node.tags)}")
        if node.glossary_terms:
            signals.append(f"glossary: {', '.join(f'`{t}`' for t in node.glossary_terms)}")
        signals_str = " · ".join(signals) or "—"

        added = []
        if requires_freshness_check(node):
            added.append("freshness gate")
        for check in checks_by_urn.get(node.urn, []):
            added.append("PII audit" if check.kind == "pii_audit" else "row count check")
        added_str = ", ".join(added) or "—"

        lines.append(f"| {i} | `{node.simple_name}` | {upstream_str} | {signals_str} | {added_str} |")

    dag_file = f"{dags_dir}/{dag_id}.py"
    lines += [
        "",
        "### Regenerate",
        "",
        "```bash",
        f"datahub-dag --target {shlex.quote(target_table)} --instance {shlex.quote(platform_instance)}",
        "```",
        "",
        f"_File: `{dag_file}` — replace `printf` commands with real SQL/dbt/Spark ETL before production._",
    ]
    return "\n".join(lines)


def _emit_result(result: GenerationResult, args: argparse.Namespace, dag_id: str) -> None:
    dag_source = result.dag_source
    if args.dry_run:
        print(f"\n{'─' * 60}\n{dag_source}\n{'─' * 60}")
        print("[dry-run] No file written and no DataHub metadata changed.")
        return

    if Path(dag_id).name != dag_id or dag_id in {".", ".."} or "\\" in dag_id:
        raise ValueError("DAG ID cannot contain path separators")
    output_directory = Path(args.output)
    output_directory.mkdir(parents=True, exist_ok=True)
    output_path = output_directory / f"{dag_id}.py"
    output_path.write_text(dag_source)
    print(f"Done. DAG saved to: {output_path}")


def _create_pr(result: GenerationResult, args: argparse.Namespace, dag_id: str) -> None:
    if args.dry_run:
        print("[dry-run] --pr skipped: no branch, commit, or PR will be created.")
        return

    for tool in ("git", "gh"):
        try:
            subprocess.run([tool, "--version"], capture_output=True, check=True)
        except (FileNotFoundError, subprocess.CalledProcessError):
            raise RuntimeError(
                f"'{tool}' is required for --pr but was not found on PATH. "
                "Install it and make sure you are authenticated."
            )

    dirty = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True
    ).stdout.strip()
    if dirty:
        raise RuntimeError(
            "Working tree has uncommitted changes — commit or stash them before using --pr."
        )

    branch = f"datahub-dag/{dag_id}"
    dags_dir = Path(args.dags_dir)
    dags_dir.mkdir(parents=True, exist_ok=True)
    dag_file = dags_dir / f"{dag_id}.py"
    dag_file.write_text(result.dag_source)

    subprocess.run(["git", "checkout", "-B", branch], check=True)
    subprocess.run(["git", "add", str(dag_file)], check=True)
    subprocess.run(
        ["git", "commit", "-m", f"feat: add {dag_id} Airflow DAG (DataHub agent)"],
        check=True,
    )
    subprocess.run(["git", "push", "-u", "origin", branch], check=True)

    pr_body = build_pr_description(
        result=result,
        dag_id=dag_id,
        target_table=result.target_table or dag_id,
        platform_instance=args.instance,
        schedule=args.schedule,
        dags_dir=args.dags_dir,
    )
    subprocess.run(
        [
            "gh", "pr", "create",
            "--title", f"feat: add {dag_id} Airflow DAG",
            "--body", pr_body,
            "--base", args.pr_base,
        ],
        check=True,
    )
    print(f"PR created on branch '{branch}'.")


def _run_agent(
    args: argparse.Namespace,
    settings: Settings,
    dag_id: str,
) -> GenerationResult:
    if args.urn:
        raise ValueError("--urn is only supported with --mode script")

    from dag_generator.agent_loop import run_dag_agent

    return run_dag_agent(
        target_table=args.target,
        platform_instance=args.instance,
        dag_id=dag_id,
        schedule=args.schedule,
        dry_run=args.dry_run,
        writeback=args.writeback,
        provider=args.provider,
        model=args.model,
        settings=settings,
    )


def _run_script(
    args: argparse.Namespace,
    settings: Settings,
    dag_id: str,
) -> GenerationResult:
    client = DataHubClient(settings.datahub_server, settings.datahub_token)
    if args.urn:
        root_urn = args.urn
        target_table = _urn_to_table_name(root_urn)
    else:
        print(f"[1/4] Searching for {args.target!r} in {args.instance!r}...")
        root_urn = client.find_urn(args.target, args.instance)
        if not root_urn:
            raise ValueError(
                f"Dataset {args.target!r} was not found in instance {args.instance!r}"
            )
        target_table = args.target

    print(f"[2/4] Traversing lineage from {target_table!r}...")
    nodes = client.get_lineage_graph(root_urn)
    if len(nodes) > settings.max_lineage_nodes:
        raise ValueError(
            f"Lineage has {len(nodes)} nodes; limit is {settings.max_lineage_nodes}"
        )
    transitive_reduction(nodes)
    sorted_nodes = topological_sort(nodes)
    print("  Execution order:", " → ".join(node.simple_name for node in sorted_nodes))

    print(f"[3/4] Rendering DAG {dag_id!r}...")
    quality_checks = recommended_quality_checks(sorted_nodes)
    dag_source = render_dag(
        sorted_nodes=sorted_nodes,
        dag_id=dag_id,
        schedule=args.schedule,
        target_table=target_table,
        platform_instance=args.instance,
        quality_checks=quality_checks,
        database_path=settings.dag_database_path_template.replace(
            "{instance}", args.instance
        ),
    )

    if args.writeback and not args.dry_run:
        print("[4/4] Writing provenance to DataHub...")
        for node in sorted_nodes:
            client.write_dag_provenance(node.urn, dag_id)
    else:
        print("[4/4] Write-back disabled")
    return GenerationResult(
        dag_source=dag_source,
        sorted_nodes=sorted_nodes,
        quality_checks=quality_checks,
        target_table=target_table,
    )


def main() -> int:
    try:
        settings = load_settings()
        args = parse_args(settings)
        settings = replace(settings, datahub_server=args.server)
        dag_id = args.dag_id or f"{args.instance}_pipeline"
        result = (
            _run_agent(args, settings, dag_id)
            if args.mode == "agent"
            else _run_script(args, settings, dag_id)
        )
        if args.pr:
            _create_pr(result, args, dag_id)
        else:
            _emit_result(result, args, dag_id)
        return 0
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1
