# Generated by DataHub DAG Generator
# Source: DataHub lineage graph — nyc_taxi_mart_v2
# DO NOT EDIT MANUALLY — regenerate with:
#   datahub-dag --target mart_daily_summary --instance nyc_taxi

from datetime import datetime, timedelta, timezone

from airflow.providers.standard.operators.bash import BashOperator
from airflow.sdk import DAG

default_args = {
    'owner': 'data_platform_team',
    'depends_on_past': True,
    'email_on_failure': True,
    'retries': 1,
    'retry_delay': timedelta(seconds=10),
}

with DAG(
    dag_id='nyc_taxi_mart_v2',
    default_args=default_args,
    schedule='@daily',
    start_date=datetime(2024, 1, 1, tzinfo=timezone.utc),
    catchup=False,
    tags=['generated_by_datahub_agent', 'nyc_taxi'],
) as dag:

    # Stage 0: raw_trips
    # DataHub URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.raw_trips,PROD)
    # Tags: daily_refresh, time_series, pii, pipeline_stage
    # Glossary: freshness_sla, pipeline_stage
    ingest_raw_trips = BashOperator(
        task_id='ingest_raw_trips',
        bash_command="printf '%s\\n' 'Running ingest for raw_trips...'",
        doc_md='Managed by DataHub DAG Generator. URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.raw_trips,PROD)',
    )

    # Freshness gate: tag: daily_refresh, glossary: freshness_sla
    freshness_check_raw_trips = BashOperator(
        task_id='freshness_check_raw_trips',
        bash_command='python - <<\'PY\'\nimport datetime\nimport sqlite3\nimport sys\nconnection = sqlite3.connect(\'/opt/airflow/demo-data/nyc_taxi.db\')\ntable = \'raw_trips\'\nupstream_tables = ()\ncandidates = (\'trip_date\', \'tpep_pickup_datetime\', \'event_time\', \'updated_at\', \'created_at\')\ndef latest_date(table_name):\n    quoted_table = table_name.replace(\'"\', \'""\')\n    columns = {row[1] for row in connection.execute(f\'PRAGMA table_info("{quoted_table}")\')}\n    timestamp_column = next((column for column in candidates if column in columns), None)\n    if timestamp_column is None:\n        raise ValueError(f\'No supported freshness column found in {table_name}: {sorted(columns)}\')\n    query = f\'SELECT MAX("{timestamp_column}") FROM "{quoted_table}"\'\n    row = connection.execute(query).fetchone()\n    latest = row[0] if row else None\n    if latest is None:\n        raise ValueError(f\'No timestamped records found in {table_name}\')\n    return datetime.datetime.fromisoformat(str(latest).replace(\'Z\', \'+00:00\')).date()\ntry:\n    downstream_latest = latest_date(table)\n    upstream_latest = max((latest_date(name) for name in upstream_tables), default=None)\nexcept (TypeError, ValueError) as exc:\n    connection.close()\n    print(exc)\n    sys.exit(2)\nconnection.close()\nprint(f\'Latest record in {table}:\', downstream_latest)\nif upstream_latest is None:\n    print(\'Root dataset establishes the freshness baseline\')\n    sys.exit(0)\nlag_days = (upstream_latest - downstream_latest).days\nprint(\'Latest direct upstream record:\', upstream_latest)\nprint(\'Downstream lag in days:\', max(lag_days, 0))\nsys.exit(0 if lag_days <= 0 else 1)\nPY',
        doc_md='Freshness gate for raw_trips',
    )

    data_audit_raw_trips = BashOperator(
        task_id='data_audit_raw_trips',
        bash_command="printf '%s\\n' 'Audit log: PII access for raw_trips'",
        doc_md='Metadata policy: pii_audit',
    )
    ingest_raw_trips >> freshness_check_raw_trips
    freshness_check_raw_trips >> data_audit_raw_trips

    # Stage 1: staging_trips
    # DataHub URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.staging_trips,PROD)
    # Tags: daily_refresh, time_series, pii, pipeline_stage
    # Glossary: freshness_sla, pipeline_stage
    transform_staging_trips = BashOperator(
        task_id='transform_staging_trips',
        bash_command="printf '%s\\n' 'Running transform for staging_trips...'",
        doc_md='Managed by DataHub DAG Generator. URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.staging_trips,PROD)',
    )

    # Freshness gate: tag: daily_refresh, glossary: freshness_sla
    freshness_check_staging_trips = BashOperator(
        task_id='freshness_check_staging_trips',
        bash_command='python - <<\'PY\'\nimport datetime\nimport sqlite3\nimport sys\nconnection = sqlite3.connect(\'/opt/airflow/demo-data/nyc_taxi.db\')\ntable = \'staging_trips\'\nupstream_tables = (\'raw_trips\',)\ncandidates = (\'trip_date\', \'tpep_pickup_datetime\', \'event_time\', \'updated_at\', \'created_at\')\ndef latest_date(table_name):\n    quoted_table = table_name.replace(\'"\', \'""\')\n    columns = {row[1] for row in connection.execute(f\'PRAGMA table_info("{quoted_table}")\')}\n    timestamp_column = next((column for column in candidates if column in columns), None)\n    if timestamp_column is None:\n        raise ValueError(f\'No supported freshness column found in {table_name}: {sorted(columns)}\')\n    query = f\'SELECT MAX("{timestamp_column}") FROM "{quoted_table}"\'\n    row = connection.execute(query).fetchone()\n    latest = row[0] if row else None\n    if latest is None:\n        raise ValueError(f\'No timestamped records found in {table_name}\')\n    return datetime.datetime.fromisoformat(str(latest).replace(\'Z\', \'+00:00\')).date()\ntry:\n    downstream_latest = latest_date(table)\n    upstream_latest = max((latest_date(name) for name in upstream_tables), default=None)\nexcept (TypeError, ValueError) as exc:\n    connection.close()\n    print(exc)\n    sys.exit(2)\nconnection.close()\nprint(f\'Latest record in {table}:\', downstream_latest)\nif upstream_latest is None:\n    print(\'Root dataset establishes the freshness baseline\')\n    sys.exit(0)\nlag_days = (upstream_latest - downstream_latest).days\nprint(\'Latest direct upstream record:\', upstream_latest)\nprint(\'Downstream lag in days:\', max(lag_days, 0))\nsys.exit(0 if lag_days <= 0 else 1)\nPY',
        doc_md='Freshness gate for staging_trips',
    )

    data_audit_staging_trips = BashOperator(
        task_id='data_audit_staging_trips',
        bash_command="printf '%s\\n' 'Audit log: PII access for staging_trips'",
        doc_md='Metadata policy: pii_audit',
    )
    transform_staging_trips >> freshness_check_staging_trips
    freshness_check_staging_trips >> data_audit_staging_trips

    # Stage 2: mart_daily_summary
    # DataHub URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.mart_daily_summary,PROD)
    # Tags: daily_refresh, pipeline_stage
    # Glossary: freshness_sla, empty_load, pipeline_stage
    aggregate_mart_daily_summary = BashOperator(
        task_id='aggregate_mart_daily_summary',
        bash_command="printf '%s\\n' 'Running aggregate for mart_daily_summary...'",
        doc_md='Managed by DataHub DAG Generator. URN: urn:li:dataset:(urn:li:dataPlatform:sqlite,nyc_taxi.main.mart_daily_summary,PROD)',
    )

    # Freshness gate: tag: daily_refresh, glossary: freshness_sla
    freshness_check_mart_daily_summary = BashOperator(
        task_id='freshness_check_mart_daily_summary',
        bash_command='python - <<\'PY\'\nimport datetime\nimport sqlite3\nimport sys\nconnection = sqlite3.connect(\'/opt/airflow/demo-data/nyc_taxi.db\')\ntable = \'mart_daily_summary\'\nupstream_tables = (\'staging_trips\',)\ncandidates = (\'trip_date\', \'tpep_pickup_datetime\', \'event_time\', \'updated_at\', \'created_at\')\ndef latest_date(table_name):\n    quoted_table = table_name.replace(\'"\', \'""\')\n    columns = {row[1] for row in connection.execute(f\'PRAGMA table_info("{quoted_table}")\')}\n    timestamp_column = next((column for column in candidates if column in columns), None)\n    if timestamp_column is None:\n        raise ValueError(f\'No supported freshness column found in {table_name}: {sorted(columns)}\')\n    query = f\'SELECT MAX("{timestamp_column}") FROM "{quoted_table}"\'\n    row = connection.execute(query).fetchone()\n    latest = row[0] if row else None\n    if latest is None:\n        raise ValueError(f\'No timestamped records found in {table_name}\')\n    return datetime.datetime.fromisoformat(str(latest).replace(\'Z\', \'+00:00\')).date()\ntry:\n    downstream_latest = latest_date(table)\n    upstream_latest = max((latest_date(name) for name in upstream_tables), default=None)\nexcept (TypeError, ValueError) as exc:\n    connection.close()\n    print(exc)\n    sys.exit(2)\nconnection.close()\nprint(f\'Latest record in {table}:\', downstream_latest)\nif upstream_latest is None:\n    print(\'Root dataset establishes the freshness baseline\')\n    sys.exit(0)\nlag_days = (upstream_latest - downstream_latest).days\nprint(\'Latest direct upstream record:\', upstream_latest)\nprint(\'Downstream lag in days:\', max(lag_days, 0))\nsys.exit(0 if lag_days <= 0 else 1)\nPY',
        doc_md='Freshness gate for mart_daily_summary',
    )

    validate_row_count_mart_daily_summary = BashOperator(
        task_id='validate_row_count_mart_daily_summary',
        bash_command='python - <<\'PY\'\nimport sqlite3\nimport sys\nconnection = sqlite3.connect(\'/opt/airflow/demo-data/nyc_taxi.db\')\ncount = connection.execute(\'SELECT COUNT(*) FROM "mart_daily_summary"\').fetchone()[0]\nconnection.close()\nprint(\'Row count:\', count)\nsys.exit(0 if count > 0 else 1)\nPY',
        doc_md='Metadata policy: row_count',
    )
    aggregate_mart_daily_summary >> freshness_check_mart_daily_summary
    freshness_check_mart_daily_summary >> validate_row_count_mart_daily_summary

    # Dependencies derived from DataHub lineage
    data_audit_raw_trips >> transform_staging_trips
    data_audit_staging_trips >> aggregate_mart_daily_summary
