"""
Render a valid Airflow DAG Python file from a topologically sorted lineage graph.

Task structure per dataset node:
  1. <verb>_<table>              — main processing task (ingest / transform / aggregate)
  2. freshness_check_<table>     — optional gate task, added when DataHub metadata
                                   indicates time-sensitivity (daily_refresh tag or
                                   Freshness SLA glossary term)

Wiring:
  <main_task> → [freshness_check_<table>] → <next_stage_main_task>

The freshness check task runs AFTER the main task and gates the next stage,
proving the pipeline has fresh data before proceeding downstream.
"""
from __future__ import annotations

from agent.datahub_client import DatasetNode
from agent.freshness_inspector import freshness_reason, requires_freshness_check


def _stage_verb(idx: int, total: int) -> str:
    if idx == 0:
        return "ingest"
    if idx == total - 1:
        return "aggregate"
    return "transform"


def render_dag(
    sorted_nodes: list[DatasetNode],
    dag_id: str,
    schedule: str = "@daily",
    owner: str = "data_platform_team",
    target_table: str = "",
    platform_instance: str = "",
) -> str:
    """Return the content of a ready-to-use Airflow DAG Python file."""
    lines: list[str] = []

    regen_cmd = f"python generate_dag.py --target {target_table} --instance {platform_instance}" \
        if target_table and platform_instance else "python generate_dag.py"

    lines += [
        "# Generated by DataHub DAG Generator Agent",
        f"# Source: DataHub lineage graph — {dag_id}",
        "# DO NOT EDIT MANUALLY — regenerate with:",
        f"#   {regen_cmd}",
        "",
        "from datetime import datetime, timedelta",
        "",
        "from airflow import DAG",
        "from airflow.operators.bash import BashOperator",
        "",
        "default_args = {",
        f'    "owner": "{owner}",',
        '    "depends_on_past": True,',
        '    "email_on_failure": True,',
        '    "retries": 1,',
        '    "retry_delay": timedelta(minutes=5),',
        "}",
        "",
        "with DAG(",
        f'    dag_id="{dag_id}",',
        "    default_args=default_args,",
        f'    schedule_interval="{schedule}",',
        "    start_date=datetime(2024, 1, 1),",
        "    catchup=False,",
        f'    tags=["generated_by_datahub_agent", "{platform_instance}"],',
        ") as dag:",
    ]

    total = len(sorted_nodes)
    # Maps urn → the last task_id that downstream stages should depend on
    gate_task: dict[str, str] = {}

    for idx, node in enumerate(sorted_nodes):
        table = node.simple_name
        verb = _stage_verb(idx, total)
        main_id = f"{verb}_{table}"
        needs_freshness = requires_freshness_check(node)
        freshness_id = f"freshness_check_{table}" if needs_freshness else None

        lines.append("")
        lines.append(f"    # ── Stage {idx}: {table} {'─' * max(0, 56 - len(table))}")
        lines.append(f"    # DataHub URN: {node.urn}")
        if node.tags:
            lines.append(f"    # Tags: {', '.join(node.tags)}")
        if node.glossary_terms:
            lines.append(f"    # Glossary: {', '.join(node.glossary_terms)}")

        lines += [
            f"    {main_id} = BashOperator(",
            f'        task_id="{main_id}",',
            f'        bash_command="echo \'Running {verb} for {table}...\'",',
            f'        doc_md="Managed by DataHub DAG Generator. URN: {node.urn}",',
            "    )",
        ]

        if freshness_id:
            reason = freshness_reason(node)
            lines.append("")
            lines.append(
                f"    # Freshness gate — DataHub metadata signals time-sensitivity: {reason}"
            )
            lines += [
                f"    {freshness_id} = BashOperator(",
                f'        task_id="{freshness_id}",',
                "        bash_command=(",
                '            "python -c \\"'
                "import sqlite3, sys, datetime; "
                f"conn = sqlite3.connect('/path/to/{platform_instance}.db'); "
                f"row = conn.execute('SELECT MAX(trip_date) FROM {table}').fetchone(); "
                "conn.close(); "
                "max_date = row[0] if row else None; "
                "print(f\\'Latest record in "
                f"{table}"
                ": {{max_date}}\\'); "
                "days = (datetime.date.today() - datetime.date.fromisoformat(max_date)).days if max_date else 999; "
                "sys.exit(0 if days <= 1 else 1)"
                '\\"\\n"',
                "        ),",
                f'        doc_md=(',
                f'            "Freshness gate for {table}.\\n"',
                f'            "Added because DataHub metadata shows: {reason}.\\n"',
                f'            "Fails if MAX(trip_date) is more than 1 day old."',
                "        ),",
                "    )",
            ]

        gate_task[node.urn] = freshness_id if freshness_id else main_id

    # ── Task dependency wiring ───────────────────────────────────────────────
    # Each node has:
    #   main_task  → the first task that runs for this node (ingest/transform/aggregate)
    #   freshness  → optional gate task that runs AFTER main_task
    #
    # Wiring pattern:
    #   main_task >> freshness_check      (freshness verifies the main task's output)
    #   upstream_gate >> main_task        (this node starts only after upstream is verified)
    #
    # gate_task[urn] = freshness_id if present, else main_id
    # This ensures that the *next* node waits until freshness is confirmed.

    lines += ["", "    # Task dependencies — derived from DataHub lineage graph"]

    for node in sorted_nodes:
        table = node.simple_name
        total_local = len(sorted_nodes)
        idx_local = sorted_nodes.index(node)
        verb = _stage_verb(idx_local, total_local)
        main_id = f"{verb}_{table}"
        freshness_id = f"freshness_check_{table}" if requires_freshness_check(node) else None

        # main_task → freshness_check (freshness runs after the main task)
        if freshness_id:
            lines.append(f"    {main_id} >> {freshness_id}")

        # upstream's gate → this node's main task (not its freshness check)
        for upstream_urn in node.upstream_urns:
            if upstream_urn in gate_task:
                lines.append(f"    {gate_task[upstream_urn]} >> {main_id}")

    lines.append("")
    return "\n".join(lines)
